config/routes.rb
Varkek::Application.routes.draw do
  
  namespace :admin do
    resources :topic_groups
    resources :topics do 
      resources :barriers do 
        resources :contexts do 
          resources :steps, except: [:index]
        end
      end
    end
    resources :users
    resources :questions do 
      resources :answers
    end
    root to: 'topics#index'
  end

  namespace :api do 
    namespace :v1 do
      resources :topics,    only: [:index, :show]
      resources :barriers,  only: [:index, :show]
      resources :contexts,  only: [:index, :show]
      resources :steps,     only: [:index, :show]
    end
  end
  
  resources :barriers, only: [:index, :show] do 
    get 'search', on: :collection
  end
  resources :contexts, only: [:show] 
  
  resources :questions, only: [:index, :show] do
    get 'search', on: :collection
  end
  resources :answers, only: [:show] 
  
  devise_for :users, :skip => [:registrations, :invitation]
  as :user do
    get 'users/edit' => 'devise/registrations#edit',   as: 'edit_user_registration'
    put 'users'      => 'devise/registrations#update', as: 'user_registration'

    get '/users/invitation/accept' => 'devise/invitations#edit',   as: 'accept_user_invitation'
    put '/users/invitation'        => 'devise/invitations#update', as: nil
  end
  
  resources :redis_stats, only: [:create]
  
  root to: 'questions#index'
end

app/models/context.rb
class Context
  include Mongoid::Document
  include Varkek::Document
  
  belongs_to :barrier
  has_many :steps
  
  field :title, type: String
  
  def expected_barriers 
    Barrier.limit(5)
  end
end

app/controllers/admin/contexts_controller.rb
module Admin
  class ContextsController < BaseController    
    before_action :set_topic
    before_action :set_barrier
    before_action :set_context, except: [:index, :new, :create]

    # GET /admin/topics/abc123/barriers/xyz789/contexts
    def index
      @contexts = @barrier.contexts
    end

    # GET /admin/topics/abc123/barriers/xyz789/contexts/ghi000
    def show
    end

    # GET /admin/topics/abc123/barriers/xyz789/contexts/new
    def new
      @context = Context.new(barrier: @barrier)
    end

    # GET /admin/topics/abc123/barriers/xyz789/contexts/ghi000/edit
    def edit
    end

    # POST /admin/topics/abc123/barriers/xyz789/contexts
    def create
      @context = @barrier.contexts.build(context_params)

      if @context.save
        redirect_to [:admin, @topic, @barrier, @context], notice: 'Context was successfully created.'
      else
        render action: 'new'
      end
    end

    # PATCH/PUT /admin/topics/abc123/barriers/xyz789/contexts/ghi000
    def update
      if @context.update(context_params)
        respond_to do |format|
          format.html { redirect_to [:admin, @topic, @barrier], status: 303, notice: 'context was successfully updated.' }
          format.json { render json: 'successful' }
        end
      else
        render action: 'edit'
      end
    end

    # DELETE /admin/topics/abc123/barriers/xyz789/contexts/ghi000
    def destroy
      @context.destroy
      redirect_to [:admin, @topic, @barrier], notice: 'Direction was successfully destroyed.'
    end

    private
      def set_topic
        @topic = Topic.find(params[:topic_id])
      end
      
      def set_barrier
        @barrier = @topic.barriers.find(params[:barrier_id])
      end
      
      def set_context
        @context = @barrier.contexts.find(params[:id])
      end
      
      # Only allow a trusted parameter "white list" through.
      def context_params
        params.require(:context).permit(:content, :title, :context)
      end
      
      def context_context
        params.permit(:context)['context']
      end
  end
end

app/controllers/api/v1/contexts_controller.rb
module Api
  module V1
    class ContextsController < Base
      
      before_filter :set_barrier, only: [:index]
            
      def index 
        if @barrier
          @contexts = @barrier.contexts
        else
          @contexts = Barrier.all
        end
        
        render "index", formats: :json, collection: @contexts
      end
      
      def show
        @context = Context.find(params[:id])
        render :show, formats: :json, object: @context
      end
      
      private 
      
        def set_barrier
          if params[:barrier_id]
            @barrier = Barrier.find(params[:barrier_id])
          end
        end
        
    end
  end
end

app/controllers/contexts_controller.rb
class ContextsController < ApplicationController
  def show
    @context = Context.find(params[:id])
  end
end

app/views/admin/contexts/_form.html.erb
<%= form_for([:admin, @topic, @barrier, @context]) do |f| %>
  <% if @context.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@context.errors.count, "error") %> prohibited this context from being saved:</h2>

      <ul>
      <% @context.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit class: 'ma-link' %>
  </div>
<% end %>

app/views/admin/contexts/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<br>
<%= link_to 'Back', [:admin, @topic, @question], class: 'ma-link' %>

app/views/admin/contexts/index.html.erb
<h1>Listing contexts</h1>

<table>
  <thead>
    <tr>
      <th>Barrier</th>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @contexts.each do |context| %>
      <tr>
        <td><%= context.barrier.title %></td>
        <td><%= context.title %></td>
        <td><%= link_to 'Show', admin_topic_barrier_context_path(@topic, @barrier, context) %></td>
        <td><%= link_to 'Edit', edit_admin_topic_barrier_context_path(@topic, @barrier, context) %></td>
        <td><%= link_to 'Destroy', admin_topic_barrier_contexts_path(@topic, @barrier), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New context', new_admin_topic_barrier_context_path(@topic, @barrier) %>

app/views/admin/contexts/new.html.erb
<h1>New Context</h1>

<%= render 'form' %>

<br>
<%= link_to 'Back', [:admin, @topic, @barrier], class: 'ma-link' %>

app/views/admin/contexts/show.html.erb
<%= link_to 'Back to Barrier ', [:admin, @topic, @barrier], { class: 'ma-link' } %>
<br>
<br>
<br>

<p>
  <strong>Topic:</strong>
  <%= @barrier.topic.title %>
</p>

<p>
  <strong>Barrier:</strong>
  <%= @barrier.title %>
</p>

<p>
  <strong>Context:</strong>
  <%= @context.title %>
</p>

<%= link_to 'Edit Context', edit_admin_topic_barrier_context_path(@topic, @barrier, @context), { class: 'ma-link' }%>
<br>
<br>
<br>

<h3>Steps</h3> 

<table class="table">
  <thead>
    <tr>
      <td class="col-md-2">Actions</td>
      <td>Title</td>
      <td>Content</td>
    </tr>
  </thead>
  
  <% @context.steps.each do |step| %>
    <tr>
      <td>
        <%= link_to 'Go To', admin_topic_barrier_context_step_path(@topic, @barrier, @context, step), class: 'ma-link' %>
        <%= link_to 'Edit', edit_admin_topic_barrier_context_step_path(@topic, @barrier, @context, step), class: 'ma-link' %>
        <%= link_to 'Delete', admin_topic_barrier_context_step_path(@topic, @barrier, @context, step), {method: :delete, 'data-conform' => 'Are you sure?', class: 'ma-link'} %>
      </td>
      <td><%= step.title %></td>
      <td><%= truncate(step.content, length: 80) %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'New Step', new_admin_topic_barrier_context_step_path(@topic, @barrier, @context), { class: 'ma-link' }%>