config/routes.rb
Varkek::Application.routes.draw do
  
  namespace :admin do
    resources :topic_groups
    resources :topics do 
      resources :barriers do 
        resources :contexts do 
          resources :steps, except: [:index]
        end
      end
    end
    resources :users
    resources :questions do 
      resources :answers
    end
    root to: 'topics#index'
  end

  namespace :api do 
    namespace :v1 do
      resources :topics,    only: [:index, :show]
      resources :barriers,  only: [:index, :show]
      resources :contexts,  only: [:index, :show]
      resources :steps,     only: [:index, :show]
    end
  end
  
  resources :barriers, only: [:index, :show] do 
    get 'search', on: :collection
  end
  resources :contexts, only: [:show] 
  
  resources :questions, only: [:index, :show] do
    get 'search', on: :collection
  end
  resources :answers, only: [:show] 
  
  devise_for :users, :skip => [:registrations, :invitation]
  as :user do
    get 'users/edit' => 'devise/registrations#edit',   as: 'edit_user_registration'
    put 'users'      => 'devise/registrations#update', as: 'user_registration'

    get '/users/invitation/accept' => 'devise/invitations#edit',   as: 'accept_user_invitation'
    put '/users/invitation'        => 'devise/invitations#update', as: nil
  end
  
  resources :redis_stats, only: [:create]
  
  root to: 'questions#index'
end

app/models/topic.rb
class Topic
  include Mongoid::Document
  include Varkek::Document
  
  has_many :barriers
  
  field :title, 
    type: String
  
  field :description, 
    type: String
  
  field :topic_group_ids, 
    type: Array, 
    default: []
    
  def topic_groups 
    topic_groups = TopicGroup.where(:_id.in => topic_group_ids)
  end  
end

app/controllers/admin/topics_controller.rb
module Admin
  class TopicsController < BaseController
  
    before_action :set_topic, only: [:show, :edit, :update, :destroy]

    # GET /admin/topics
    def index
      @topics = Topic.all
    end

    # GET /admin/topics/1
    def show
      respond_to do |f|
        f.html  { render }
        
        f.pdf {
          
          # pdf = Prawn::Document.new
          # pdf.text "Title: #{@topic.title}"
          # pdf.text "Description: #{@topic.description}"
          
          # pdf.move_down 10
          # pdf.text "Topic Groups:"
          # @topic.topic_groups.each do |topic_group|
          #   pdf.text " =>  #{topic_group.title}"
          # end
          
          # pdf.move_down 20
          # pdf.text "Questions"
          
          # @topic.questions.each do |question|
          #   question.contexts.each do |context|
          #     pdf.text context == 0 ? "Default Context" : "Context #{context}"
          #     pdf.move_down 2
              
          #     # responses
          #     question.responses.select{ |r| context == r.context }.each do |response|
          #       pdf.text "-------- Response"
          #       pdf.text "Title: #{response.title}"
          #       pdf.text "Content: #{response.content}"
          #       pdf.move_down 10
          #     end
              
          #     # directions
          #     question.directions.select{ |d| context == d.context }.each do |direction|
          #       pdf.text "-------- Direction"
          #       pdf.text "Approach: #{direction.approach}"
          #       pdf.text "Cotent: #{direction.content}"
          #       pdf.move_down 10
          #     end
              
          #     # transitions
          #     question.transitions.select{ |t| context == t.context }.each do |transition|
          #       pdf.text "-------- Transition"
          #       pdf.text "Title: #{transition.title}"
          #       pdf.text "Content: #{transition.content}"
          #     end
              
          #     pdf.move_down 20
          #   end
          # end
          
          # send_data pdf.render, type: "application/pdf", disposition: "inline"
        }
      end
    end

    # GET /admin/topics/new
    def new
      @topic = Topic.new
    end

    # GET /admin/topics/1/edit
    def edit
    end

    # POST /admin/topics
    def create
      @topic = Topic.new(topic_params)

      if @topic.save
        redirect_to [:admin, @topic], notice: 'Topic was successfully created.'
      else
        render action: 'new'
      end
    end

    # PATCH/PUT /admin/topics/1
    def update
      if @topic.update(topic_params)
        redirect_to [:admin, @topic], notice: 'Topic was successfully updated.'
      else
        render action: 'edit'
      end
    end

    # DELETE /admin/topics/1
    def destroy
      @topic.destroy
      redirect_to admin_topics_url, notice: 'Topic was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_topic
        @topic = Topic.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def topic_params
        hash  = params.require(:topic).permit(:title, :description)
        
        # OBJECTIVE - come to 2 situations
        # 1. "topic_group_ids" => ["1", "2"]
        # 2. "topic_group_ids" => []
        # 
        tgids = params.require(:topic).permit(:topic_group_ids => [])
        topic_group_ids = tgids.empty? ? {"topic_group_ids" => []} : tgids
        new_hash = hash.merge(topic_group_ids)
    
        new_hash
      end
  
  end
end

app/controllers/api/v1/topics_controller.rb
module Api
  module V1
    class TopicsController < Base
      
      def index 
        @topics = Topic.all
        render :index, formats: :json, collection: @topics
      end
      
      def show
        @topic = Topic.find(params[:id])
        render :show, formats: :json, object: @topic
      end
      
    end
  end
end

app/helpers/admin/topics_helper.rb
module Admin::TopicsHelper
  
  def display_group_topic_names(topic)
    result = ""
    topic.topic_groups.each do |group|
      result += "<span class='btn-sm btn-warning'>#{group.title}</span><br /><br />"
    end
    result
  end 
  
  def list_group_topic_names(topic)
    
    result = "<p><b>Topic Groups:</b></p>"
    result += "<ul>"
    topic.topic_groups.each do |group|
      result += "<li>#{group.title}</li>"
    end
    result += "</ul>"
    
    
  end
end

app/views/admin/topics/_barriers_list.html.erb
<div class='panel panel-default'>
  <div class='panel-heading'>Barriers</div>
  <!-- <div class='panel-body'></div> -->
  <ul class='list-group'>
    <% barriers.each do |barrier| %>
      <li class='list-group-item'>
        <%= link_to 'Go To', admin_topic_barrier_path(topic, barrier), {class: 'btn btn-default btn-sm'} %>
        <%= link_to 'Delete', [:admin, topic, barrier], {class: 'btn btn-default btn-sm', method: :delete, "data-confirm" => 'Are you sure?' } %>&nbsp;
        <%= barrier.title %>
      </li>
    <% end %>
    <li class='list-group-item'>
      <%= button_to 'New Barrier', new_admin_topic_barrier_path(topic), {method: :get, class: 'btn btn-success btn-sm'} %>
    </li>
  </ul>
</div>

app/views/admin/topics/_form.html.erb
<%= form_for([:admin, @topic], role: 'form') do |f| %>
  <% if   @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this admin_topic from being saved:</h2>
      <ul>
        <% @topic.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_field :description, class: 'form-control' %>
  </div>
  
  <br />
  
  <% TopicGroup.all.each do |tg| %>
    <div class="checkbox">
      <label>
        <%= check_box_tag "topic[topic_group_ids][]", tg.id.to_s, @topic.topic_group_ids.include?(tg.id.to_s), { class: 'ma-link' } %><%= tg.title %><br>
      </label>
    </div>
  <% end %>
  
  <br />
  
  <div class="form-group">
    <%= f.submit class: 'ma-link' %>
  </div>
<% end %>

app/views/admin/topics/edit.html.erb
<h1>Editing admin_topic</h1>

<%= render 'form' %>

<br>
<%= link_to 'Show', [:admin, @topic], class: 'ma-link' %>
<%= link_to 'Back', admin_topics_path, class: 'ma-link' %>

app/views/admin/topics/index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th class='col-md-2'></th>
      <th class='col-md-4'>Title</th>
      <th class='col-md-3'>Groups</th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td>
          <%= link_to 'Go to', [:admin, topic], { class: 'ma-link'} %>
          <%= link_to 'PDF',  admin_topic_path(topic, format: 'pdf'), { class: 'ma-link'} %>
          <%= link_to 'Destroy', [:admin, topic], {method: :delete, 'data-conform' => 'Are you sure?', class: 'ma-link'} %>
        </td>
        <td><%= topic.title %></td>
        <td><%= display_group_topic_names(topic).html_safe %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class='sub-table-links'>
  <%= link_to 'New Topic', new_admin_topic_path, { class: 'ma-link'} %>
</div>

app/views/admin/topics/new.html.erb
<%= render 'form' %>

<br>

<%= link_to 'Back', admin_topics_path, { class: 'btn btn-default btn-small'} %>

app/views/admin/topics/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @topic.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @topic.description %>
</p>

<%= list_group_topic_names(@topic).html_safe %>

<br />

<%= link_to 'Edit', edit_admin_topic_path(@topic), { class: 'ma-link'} %>
<%= link_to 'Back to all Topics', admin_topics_path, {class: 'ma-link'} %>
<br>
<br>
<br>

<%= render partial: 'barriers_list', locals: {topic: @topic, barriers: @topic.barriers} %>