config/routes.rb
Varkek::Application.routes.draw do
  
  namespace :admin do
    resources :topic_groups
    resources :topics do 
      resources :barriers do 
        resources :contexts do 
          resources :steps, except: [:index]
        end
      end
    end
    resources :users
    resources :questions do 
      resources :answers
    end
    root to: 'topics#index'
  end

  namespace :api do 
    namespace :v1 do
      resources :topics,    only: [:index, :show]
      resources :barriers,  only: [:index, :show]
      resources :contexts,  only: [:index, :show]
      resources :steps,     only: [:index, :show]
    end
  end
  
  resources :barriers, only: [:index, :show] do 
    get 'search', on: :collection
  end
  resources :contexts, only: [:show] 
  
  resources :questions, only: [:index, :show] do
    get 'search', on: :collection
  end
  resources :answers, only: [:show] 
  
  devise_for :users, :skip => [:registrations, :invitation]
  as :user do
    get 'users/edit' => 'devise/registrations#edit',   as: 'edit_user_registration'
    put 'users'      => 'devise/registrations#update', as: 'user_registration'

    get '/users/invitation/accept' => 'devise/invitations#edit',   as: 'accept_user_invitation'
    put '/users/invitation'        => 'devise/invitations#update', as: nil
  end
  
  resources :redis_stats, only: [:create]
  
  root to: 'questions#index'
end

app/models/answer.rb
class Answer 
  include Mongoid::Document
  include Varkek::Document
  
  field :title, type: String
  field :content, type: String
  
  belongs_to :question
end

app/models/barrier.rb
class Barrier
  include Mongoid::Document
  include Varkek::Document
  include Mongoid::Search
  
  belongs_to :topic
  has_many :contexts
  has_many :questions
  
  field :title, type: String
  
  search_in :title
end

app/models/card.rb
class Card
  include Mongoid::Document

  field :title, type: String
  field :description, type: String

  embeds_many :paragraphs
  accepts_nested_attributes_for :paragraphs
end

app/models/context.rb
class Context
  include Mongoid::Document
  include Varkek::Document
  
  belongs_to :barrier
  has_many :steps
  
  field :title, type: String
  
  def expected_barriers 
    Barrier.limit(5)
  end
end

app/models/direction.rb
class Direction
  include Mongoid::Document
  include Varkek::Document
  
  field :order, 
    type: Integer
  
  field :approach, 
    type: String
  
  field :content, 
    type: String
  
  field :context, 
    type: Integer
  
  embedded_in :question
end

app/models/link.rb
class Link
  include Mongoid::Document
  field :kind, type: String
  field :content, type: String
  
  belongs_to :topic
end

app/models/question.rb
class Question
  include Mongoid::Document
  include Mongoid::Search
  include Varkek::Document
  include RedisStat::Statable
  
  field :title, type: String
  field :content, type: String
  
  has_many :answers
  
  search_in :title, answers: :title
end

app/models/quote.rb
class Quote
  include Mongoid::Document
  include Varkek::Document
  
  field :content, 
    type: String
  
  field :author, 
    type: String
  
  embedded_in :question
end

app/models/response.rb
class Response
  include Mongoid::Document
  include Varkek::Document
  
  field :title, 
    type: String
    
  field :content, 
    type: String
    
  field :context, 
    type: Integer  
  
  embedded_in :question
end

app/models/step.rb
class Step
  include Mongoid::Document
  include Varkek::Document
  
  belongs_to :context
  has_many :transitions
  
  field :title, 
    type: String
    
  field :content, 
    type: String
end

app/models/topic.rb
class Topic
  include Mongoid::Document
  include Varkek::Document
  
  has_many :barriers
  
  field :title, 
    type: String
  
  field :description, 
    type: String
  
  field :topic_group_ids, 
    type: Array, 
    default: []
    
  def topic_groups 
    topic_groups = TopicGroup.where(:_id.in => topic_group_ids)
  end  
end

app/models/topic_group.rb
class TopicGroup
  include Mongoid::Document
  include Varkek::Document
  
  field :title, 
    type: String
  
  def topics
    Topic.any_in(topic_group_ids: self.id.to_s)
  end
end

app/models/transition.rb
class Transition
  include Mongoid::Document
  include Varkek::Document
  
  belongs_to :step
  
  field :content, 
    type: String
  
  field :title, 
    type: String
    
  field :context, 
    type: Integer
end

app/models/user.rb
class User
  include Mongoid::Document
  include Varkek::Document
  
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :registerable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""
  
  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String
end

app/controllers/admin/answers_controller.rb
module Admin
  class AnswersController < BaseController    
    before_action :set_question
    before_action :set_answer, except: [:index, :new, :create]

    # GET /admin/questions/123abc/answers
    def index
      @answers = @questions.answers
    end

    # GET /admin/questions/123abc/answers/321xyz
    def show
    end

    # GET /admin/questions/123abc/answers/new
    def new
      @answer = Answer.new
    end

    # GET /admin/questions/123abc/answers/321xyz/edit
    def edit
    end

    # POST /admin/questions/123abc/answers
    def create    
      @answer = @question.answers.build(params_answer)
      
      if @answer.save
        redirect_to admin_question_answer_path(@question, @answer), notice: 'Answer was successfully created.'
      else
        render action: 'new'
      end
    end

    # PATCH/PUT /admin/questions/123abc/answers/321xyz
    def update
      if @answer.update(params_answer)
        redirect_to [:admin, @question, @answer], notice: 'Answer was successfully updated.'
      else
        render action: 'edit'
      end
    end

    # DELETE /admin/questions/123abc/answers/321xyz
    def destroy
      @answer.destroy
      redirect_to [:admin, @question], notice: 'Answer was successfully destroyed.'
    end
    
    private
      def set_question
        @question = Question.find(params[:question_id])
      end
    
      def set_answer
        @answer = @question.answers.find(params[:id])
      end

      def params_answer
        params.require(:answer).permit(:question_id, :title, :content)
      end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bridges_helper.rb
module BridgesHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/directions_helper.rb
module DirectionsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/admin/answers/_form.html.erb
<%= form_for([:admin, @question, @answer], role: 'form') do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  
  <div class="form-group">
    <%= f.label :content %><br>
    <%= f.text_field :content, class: 'form-control' %>
  </div>
  
  <div class="actions">
    <%= f.submit class: 'ma-link' %>
  </div>
<% end %>

app/views/admin/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render 'form' %>

<br>
<%= link_to 'Back', [:admin, @question, @answer], class: 'ma-link' %>

app/views/admin/answers/index.html.erb
<h1>Listing answers</h1>

<table>
  <thead>
    <tr>
      <th>Question</th>
      <th>Title</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @answers.each do |answer| %>
      <tr>
        <td><%= answer.question.title %></td>
        <td><%= answer.title %></td>
        <td><%= link_to 'Show', admin_question_answer_path(@question, answer) %></td>
        <td><%= link_to 'Edit', edit_admin_topic_question_path(@question, answer) %></td>
        <td><%= link_to 'Destroy', admin_question_answers_path(@question, answer), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Answer', new_admin_topic_question_path(@topic) %>

app/views/admin/answers/new.html.erb
<h1>New Answer</h1>

<%= render 'form' %>

<br>
<%= link_to 'Back', [:admin, @question], class: 'ma-link' %>

app/views/admin/answers/show.html.erb
<%= link_to 'Back to Question', [:admin, @question], { class: 'ma-link' } %>
<br>
<br>
<br>

<p>
  <strong>Question:</strong>
  <%= @question.title %>
</p>

<%= link_to 'Go to Question', admin_question_path(@question), { class: 'ma-link' }%>
<br>
<br>

<p>
  <strong>Title:</strong>
  <%= @answer.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @answer.content %>
</p>


<%= link_to 'Edit Answer', edit_admin_question_answer_path(@question, @answer), { class: 'ma-link' }%>