config/routes.rb
Varkek::Application.routes.draw do
  
  namespace :admin do
    resources :topic_groups
    resources :topics do 
      resources :barriers do 
        resources :contexts do 
          resources :steps, except: [:index]
        end
      end
    end
    resources :users
    resources :questions do 
      resources :answers
    end
    root to: 'topics#index'
  end

  namespace :api do 
    namespace :v1 do
      resources :topics,    only: [:index, :show]
      resources :barriers,  only: [:index, :show]
      resources :contexts,  only: [:index, :show]
      resources :steps,     only: [:index, :show]
    end
  end
  
  resources :barriers, only: [:index, :show] do 
    get 'search', on: :collection
  end
  resources :contexts, only: [:show] 
  
  resources :questions, only: [:index, :show] do
    get 'search', on: :collection
  end
  resources :answers, only: [:show] 
  
  devise_for :users, :skip => [:registrations, :invitation]
  as :user do
    get 'users/edit' => 'devise/registrations#edit',   as: 'edit_user_registration'
    put 'users'      => 'devise/registrations#update', as: 'user_registration'

    get '/users/invitation/accept' => 'devise/invitations#edit',   as: 'accept_user_invitation'
    put '/users/invitation'        => 'devise/invitations#update', as: nil
  end
  
  resources :redis_stats, only: [:create]
  
  root to: 'questions#index'
end

app/models/barrier.rb
class Barrier
  include Mongoid::Document
  include Varkek::Document
  include Mongoid::Search
  
  belongs_to :topic
  has_many :contexts
  has_many :questions
  
  field :title, type: String
  
  search_in :title
end

app/controllers/admin/barriers_controller.rb
module Admin
  class BarriersController < BaseController    
    before_action :set_topic
    before_action :set_barrier, except: [:index, :new, :create]

    # GET /admin/topics/123abc/barriers
    def index
      @barriers = @topic.barriers      
    end

    # GET /admin/topics/123abc/barriers/321xyz
    def show
    end

    # GET /admin/topics/123abc/barriers/new
    def new
      @barrier = Barrier.new
    end

    # GET /admin/topics/123abc/barriers/321xyz/edit
    def edit
    end

    # POST /admin/topics/123abc/barriers
    def create    
      @barrier = @topic.barriers.build(barrier_params)
      
      if @barrier.save
        redirect_to admin_topic_path(@topic), notice: 'barrier was successfully created.'
      else
        render action: 'new'
      end
    end

    # PATCH/PUT /admin/topics/123abc/barriers/321xyz
    def update
      if @barrier.update(barrier_params)
        redirect_to [:admin, @topic, @barrier], notice: 'barrier was successfully updated.'
      else
        render action: 'edit'
      end
    end

    # DELETE /admin/topics/123abc/barriers/321xyz
    def destroy
      @barrier.destroy
      redirect_to [:admin, @topic], notice: 'barrier was successfully destroyed.'
    end
    
    # POST /admin/topics/123abc/barriers/321xyz/add_context
    def add_context
      if @barrier.add_context
        redirect_to [:admin, @topic, @barrier]
      else
        redirect_to [:admin, @topic, @barrier], notice: 'Error adding context'
      end
    end
    
    # DELETE /admin/topics/123abc/barriers/321xyz/delete_context
    def delete_context
      if @barrier.delete_context(barrier_context)
        redirect_to [:admin, @topic, @barrier]
      else
        redirect_to [:admin, @topic, @barrier], notice: 'Error deleting context'
      end
    end

    private
      # load the parent Topic object
      def set_topic 
        @topic = Topic.find(params[:topic_id])
      end
      
      # Use callbacks to share common setup or constraints between actions.
      def set_barrier
        @barrier = @topic.barriers.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def barrier_params
        params.require(:barrier).permit(:topic_id, :title)
      end
      
      def barrier_context
        params.require(:barrier).permit(:context)['context'].to_i
      end
  end
end

app/controllers/api/v1/barriers_controller.rb
module Api
  module V1
    class BarriersController < Base
      
      before_filter :set_topic, only: [:index]
            
      def index 
        if @topic
          @barriers = @topic.barriers
        else 
          @barriers = Barrier.all
        end
        
        render "index", formats: :json, collection: @barriers
      end
      
      def show
        @barrier = Barrier.find(params[:id])
        render :show, formats: :json, object: @barrier
      end
    
      private 
      
        def set_topic
          if params[:topid_id]
            @topic = Topic.find(params[:topic_id])
          end
        end
        
    end
  end
end

app/controllers/barriers_controller.rb
class BarriersController < ApplicationController
  def index
  end
  
  def show 
    @barrier = Barrier.find(params[:id])
  end
  
  def search 
    # @barriers = Barrier.where(title: /#{params_search}/)
    @barriers = Barrier.all
    render :index
  end
  
  private 
    def params_search
      params.permit(:search_query)
    end
    
    def words_four_chars_or_greater
      result = []
      words = params_search.split(/\s/)
      words.map{ |word| result << word if word.length > 3 }
      result
    end
end

app/views/admin/barriers/_form.html.erb
<%= form_for([:admin, @topic, @barrier]) do |f| %>
  <% if @barrier.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@barrier.errors.count, "error") %> prohibited this barrier from being saved:</h2>

      <ul>
      <% @barrier.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit class: 'ma-link' %>
  </div>
<% end %>

app/views/admin/barriers/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<br>
<%= link_to 'Back', [:admin, @topic, @question], class: 'ma-link' %>

app/views/admin/barriers/index.html.erb
<h1>Listing questions</h1>

<table>
  <thead>
    <tr>
      <th>Topic</th>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.topic.title %></td>
        <td><%= question.content %></td>
        <td><%= link_to 'Show', admin_topic_question_path(@topic, question) %></td>
        <td><%= link_to 'Edit', edit_admin_topic_question_path(@topic, question) %></td>
        <td><%= link_to 'Destroy', admin_topic_questions_path(@topic), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_admin_topic_question_path(@topic) %>

app/views/admin/barriers/new.html.erb
<h1>New Barrier</h1>

<%= render 'form' %>

<br>
<%= link_to 'Back', [:admin, @topic], class: 'ma-link' %>

app/views/admin/barriers/show.html.erb
<%= link_to 'Back to Topics ', [:admin, @topic], { class: 'ma-link' } %>
<br>
<br>
<br>

<p>
  <strong>Topic:</strong>
  <%= @barrier.topic.title %>
</p>

<p>
  <strong>Barrier:</strong>
  <%= @barrier.title %>
</p>

<%= link_to 'Edit Barrier', edit_admin_topic_barrier_path(@topic, @barrier), { class: 'ma-link' }%>
<br>
<br>
<br>

<h3>Contexts</h3> 

<table class="table">
  <thead>
    <td class="col-md-2">Actions</td>
    <td>Context</td>
  </thead>
  <% @barrier.contexts.each do |context| %>
  <tr>
    <td>
      <%= link_to 'Go To', admin_topic_barrier_context_path(@topic, @barrier, context), class: "ma-link" %>
      <%= link_to 'Edit', edit_admin_topic_barrier_context_path(@topic, @barrier, context), class: "ma-link" %>
      <%= link_to 'Delete', admin_topic_barrier_context_path(@topic, @barrier, context), {method: :delete, 'data-conform' => 'Are you sure?', class: 'ma-link'} %>
    </td>
    <td><%= context.title %></td>
  </tr>
  <% end %>
</table>

<%= link_to 'New Context', new_admin_topic_barrier_context_path(@topic, @barrier), { class: 'ma-link' }%>